# Generated by Django 5.2.5 on 2025-08-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_season_season_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
    ]
