# Generated by Django 5.2.5 on 2025-08-20 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('total_event_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_placement', models.IntegerField()),
                ('season_points', models.FloatField(default=0)),
                ('average_points', models.FloatField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=3)),
                ('doty_points', models.FloatField(default=0.0)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.competitor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
        ),
    ]
