# Generated by Django 5.2.5 on 2025-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_remove_event_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
